// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAam0t0WeFvUT8Pl0mvGZK8rdv047iNbQU',
    appId: '1:34171611660:web:797e2e22c64e3981df5c29',
    messagingSenderId: '34171611660',
    projectId: 'gps-app-bd1e2',
    authDomain: 'gps-app-bd1e2.firebaseapp.com',
    storageBucket: 'gps-app-bd1e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXXRaWlW8hEN2HGtVYcQoRcERdfd2OqjE',
    appId: '1:34171611660:android:98c6e701ca82ef04df5c29',
    messagingSenderId: '34171611660',
    projectId: 'gps-app-bd1e2',
    storageBucket: 'gps-app-bd1e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIduvS_Rj1Tz8e05bHA-_QiqhI3g4cylY',
    appId: '1:34171611660:ios:de839f5123588041df5c29',
    messagingSenderId: '34171611660',
    projectId: 'gps-app-bd1e2',
    storageBucket: 'gps-app-bd1e2.appspot.com',
    iosBundleId: 'com.example.gpsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMCreC6OOD4au7BU7OlCTFukpROsjX9Ek',
    appId: '1:866553009168:ios:f48d06df3fc42651406695',
    messagingSenderId: '866553009168',
    projectId: 'app12-minhas-viagens',
    storageBucket: 'app12-minhas-viagens.appspot.com',
    iosClientId: '866553009168-qtrpa2egbtvtuakjeqa6aq1u7f9vs8p7.apps.googleusercontent.com',
    iosBundleId: 'com.example.app12MinhasViagens.RunnerTests',
  );
}